name: Notify of any events today

on:
  schedule:
  - cron: '55 12 * * *'
  # Vancouver time, this is 5:55am, which should be before most events start.

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Notify of events
        run: python events